charts/postgres/Chart.yaml, charts/postgres/README.md, charts/postgres/templates/_helpers.tpl, charts/postgres/templates/serviceaccount.yaml, charts/postgres/templates/statefulset.yaml, charts/postgres/tests/service-account_test.yaml, charts/postgres/values.schema.json, charts/postgres/values.yaml
Allow configuring a custom service account for the postgres pod.
integration with service meshes & ability to not mount the SA entirely.
None, should be backwards-compatible
- fixes #
=> [postgres] added support for service account configuration

.github/workflows/pull-request.yaml
External Merge requests belongs to a different repository, so the checkout actions needs to checkout the remote Repo.
=> Fix GitHub Actions: Checkout external merge request repositories

charts/mariadb/CHANGELOG.md, charts/mariadb/Chart.yaml, charts/mariadb/templates/_helpers.tpl, charts/mariadb/templates/secret.yaml
Use a default randomized password, at initial mariadb installation / initialization
Easier initial setup
/ 
#34 
/
=> [mariadb] Default randomized password

charts/rabbitmq/CHANGELOG.md, charts/rabbitmq/Chart.yaml, charts/rabbitmq/templates/statefulset.yaml
Always copy the erlang cookie, giving it the right permissions
Running RabbitMQ after restart
- fixes #31
=> [rabbitmq]: Fix erlang cookie copy / access rights

charts/nginx/CHANGELOG.md, charts/nginx/Chart.yaml, charts/nginx/artifacthub-repo.yml
Fix the repositoryID in the file "artifacthub-repo.yml", so that in Artifacthub the Repository is viewed as Verified Publisher
=> [nginx] fix artifacthub-repo id

charts/rabbitmq/CHANGELOG.md, charts/rabbitmq/Chart.yaml, charts/rabbitmq/README.md, charts/rabbitmq/templates/_helpers.tpl, charts/rabbitmq/templates/configmap.yaml, charts/rabbitmq/templates/statefulset.yaml, charts/rabbitmq/values.schema.json, charts/rabbitmq/values.yaml
Add support for installing 3rd party plugins from URLs via a new `installPlugins` value. This will automatically add another init container (Still based on busybox) that downloads plugins and automatically enables them in the RabbitMQ config.
- Easy installation of 3rd-party plugins by providing download URLs
- Automatic plugin name extraction and configuration
- No manual intervention required
- Plugin download failures will prevent pod startup
- Users must ensure plugin compatibility with RabbitMQ version
- (Please inform me if I should create a matching issue for such ideas/changes beforehand)
Example usage:
```yaml
installPlugins:
- https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v4.1.0/rabbitmq_delayed_message_exchange-4.1.0.ez
```
=> [rabbitmq]: add support to automatically download and enable 3rd party plugins

charts/postgres/Chart.yaml, charts/postgres/README.md, charts/postgres/templates/statefulset.yaml, charts/postgres/values.schema.json, charts/postgres/values.yaml
Add support for persistentVolumeClaimRetentionPolicy
Enable changing Persistent Volume Claim Retention Policy for the Statefulset
(We used this feature in the old Bitnami chart)
=> [postgres] chore: add support for persistentVolumeClaimRetentionPolicy

charts/rabbitmq/CHANGELOG.md, charts/rabbitmq/Chart.yaml, charts/rabbitmq/templates/statefulset.yaml, charts/rabbitmq/values.yaml
Add the ability for custom init containers / postStart scripts
Custom initContainers and postStart scripts
None that I know of
- fixes #105
=> [rabbitmq] Custom init containers / post start scripts

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml
Adds the option to select the `zookeeper` label in the issue templates.
=> Add zookeeper label to issue templates

charts/mongodb/CHANGELOG.md, charts/mongodb/Chart.yaml, charts/mongodb/README.md, charts/mongodb/templates/custom-user-script.yaml, charts/mongodb/templates/custom-user-secret.yaml, charts/mongodb/templates/statefulset.yaml, charts/mongodb/values.yaml
Adds support to create a custom user at initialization. 
Create a custom user for a new database with the initialization. Takes away a few manual steps to use this chart.
=> [mongodb] add custom user creation at initialization

charts/mongodb/CHANGELOG.md, charts/redis/CHANGELOG.md, charts/redis/Chart.yaml, charts/redis/templates/statefulset.yaml
Use fqdn for redis master to avoid problems when reaching sentinels from other namespaces:
* currently only the shortened dns is returned:
```yaml
redis-cli -u redis://redis-sentinel.redis:26379
redis-sentinel.redis:26379> sentinel get-master-addr-by-name mymaster
1) "redis-0.redis-headless"
2) "6379"
```
* this works from the same namespace, but from other namespaces we have to use the extended one:
```terminal
nslookup redis-0.redis-headless
Server:         10.100.0.10
Address:        10.100.0.10#53
** server can't find redis-0.redis-headless: NXDOMAIN
```
* using extended one works:
```terminal
nslookup redis-0.redis-headless.redis
Server:         10.100.0.10
Address:        10.100.0.10#53
Name:   redis-0.redis-headless.redis.svc.cluster.local
Address: 172.24.22.44
;; Got recursion not …
```
=> [redis] return fqdn for sentinel master lookup

charts/keycloak/Chart.lock, charts/keycloak/Chart.yaml, charts/keycloak/README.md, charts/keycloak/templates/deployment.yaml, charts/keycloak/values.schema.json, charts/keycloak/values.yaml
Support for adding extra environment variables from an existing secret to the keycloak container.
For example, it can be used for providing credentials in an init or migration script.
=> [keycloak] add support for extra env vars from an existing secret

.github/workflows/auto-label.yaml
This prevents the `auto-label` workflow to add the label `_No response_` when the user hasn't selected a helm chart the issue applies to.
=> [auto-label] Don't add `_No response_` as label

charts/postgres/CHANGELOG.md, charts/postgres/Chart.yaml, charts/postgres/templates/configmap.yaml
Add listen_addresses = '*'  to default postgresql.conf and a default pg_hba.conf.
The default configmaps will now be working better and no customization from users will be needed
- fixes #160
=> [Postgres] update default postgres config files

charts/keycloak/CHANGELOG.md, charts/keycloak/Chart.yaml, charts/keycloak/README.md, charts/keycloak/templates/deployment.yaml, charts/keycloak/values.schema.json, charts/keycloak/values.yaml
Replaces the deprecated and removed start parameter `proxy` with `proxyheaders`, `proxyProtocolEnabled`, `proxyTrustedAddresses`
Proxy configuration will not crash the keycloak deployment. 
- fixes #159
=> [keycloak] replace deprecated 'proxy' with new proxy parameters

charts/nginx/Chart.lock, charts/nginx/Chart.yaml, charts/nginx/templates/deployment.yaml, charts/zookeeper/Chart.lock, charts/zookeeper/Chart.yaml, charts/zookeeper/templates/statefulset.yaml
- Use the helper-function from the common chart to render the security context for openshift-clusters (nginx and zookeeper chart)
- Prevents deployment failures on OpenShift due to unsupported security context fields.
- I havn't detected any drawbacks in our tests.
=> [Zookeeper] [Nginx] Change nginx and zookeeper security-context to use helper-function

charts/minio/CHANGELOG.md, charts/minio/Chart.yaml, charts/minio/README.md, charts/minio/templates/deployment.yaml, charts/minio/values.schema.json, charts/minio/values.yaml
Adds more options to configure the minio server via environment variables. 
The configuration of the minio server is standardized and documented
Adds more options and complexity to the chart
=> [minio] add more configuration options for the minio server

charts/redis/Chart.lock, charts/redis/Chart.yaml, charts/redis/templates/statefulset.yaml
> I will make a series of smaller PR to introduce common v1.1.1 and make all the charts Openshift ready. 
Openshift handles security context configuration in a special way. This changes makes sure, the redis chart runs in a openshift cluster with the changes made in common v1.1.1 
Tested on Openshift Version : 4.19.12 
Runnin on Openshift
None
None
-
=> [redis] make redis run on openshift

charts/ghost/CHANGELOG.md, charts/ghost/Chart.yaml
Because the current Ghost icon can not be used from artifact-hub, we created a new icon. 
The Helm-Chart Icon will be shown in Artifact-hub
=> [ghost] switch helm-chart icon to a new svg

charts/rabbitmq/CHANGELOG.md, charts/rabbitmq/Chart.yaml, charts/rabbitmq/templates/statefulset.yaml
Adding fields that are automatically generated by StatefulSet
Deployment orchestrators (such as ArgoCD) will not report constant 'diff' on STS object.
Not found
N/A
Tested on own cluster
=> [rabbitmq] Add automatically generated fields to volumeClaimTemplates

charts/mongodb/Chart.lock, charts/mongodb/Chart.yaml, charts/mongodb/templates/statefulset.yaml
> I will make a series of smaller PR to introduce common v1.1.1 and make all the charts Openshift ready. 
Openshift handles security context configuration in a special way. This changes makes sure, the ghost chart runs in a openshift cluster with the changes made in common v1.1.1 
Tested on Openshift Version : 4.19.12 
Runs on Openshift
None
None
None
=> [mongodb] make mongodb run on openshift

charts/rabbitmq/Chart.lock, charts/rabbitmq/Chart.yaml, charts/rabbitmq/README.md, charts/rabbitmq/templates/statefulset.yaml, charts/rabbitmq/values.yaml, charts/valkey/values.schema.json
> I will make a series of smaller PR to introduce common v1.1.1 and make all the charts Openshift ready. 
Openshift handles security context configuration in a special way. This changes makes sure, the rabbitmq chart runs in a openshift cluster with the changes made in common v1.1.1 
Tested on Openshift Version : 4.19.12 
Runs on Openshift cluster
In case somebody has used `securitContext` for a custom configuration, must rename the var to `containerSecurityContex`
None
The initcontianers have now the same securityContext as the actual running contianer. I can't see a need for a separate scrutiycontext configuration.
=> [rabbitmq] make rabbitmq run on openshift
